### ISSUE TITLE
Travis CI Page.setLifecycleEventsEnabled error

### ISSUE THREAD

**Issue by mhluska** [GoogleChrome/lighthouse-ci#115]
Running `lhci autorun` in Travis CI eventually gives this error:

```
Runtime error encountered: Protocol error (Page.setLifecycleEventsEnabled): 'Page.setLifecycleEventsEnabled' wasn't found
Error: Protocol error (Page.setLifecycleEventsEnabled): 'Page.setLifecycleEventsEnabled' wasn't found
    at Function.fromProtocolMessage (/home/travis/.nvm/versions/node/v11.12.0/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:132:19)
    at callback.resolve.Promise.resolve.then._ (/home/travis/.nvm/versions/node/v11.12.0/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:123:25)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Also, the the return status code is still 0 so the build passes.

Also tested with node 10.11, same result.

**Comment by patrickhulce** [comment]
This error message means that the Chrome version is very, very old. Only Chrome stable and later is supported. How are you getting Chrome in your environment?

**Comment by mhluska** [comment]
I'm using:

```
    addons:
      addons:
        chrome: stable
```

But now that I think about it, that should probably say:

```
    addons:
        chrome: stable
```

**Comment by mhluska** [comment]
Seems to be working fine now. Thanks! Closing.
