### ISSUE TITLE
[0.3.5] Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by pats** [GoogleChrome/lighthouse-ci#133]
Hi,

Version 0.3.5 seems doesn't work

```
✅✅  .lighthouseci/ directory writable
✅✅  Configuration file found
✅✅  Chrome installation found
⚠️   GitHub token not set
Healthcheck passed!

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at PuppeteerManager._getBrowser (C:\Users\Patrycjusz.Szydlo\AppData\Roaming\npm\node_modules\@lhci\cli\src\collect\puppeteer-manager.js:27:23)
    at PuppeteerManager.invokePuppeteerScriptForUrl (C:\Users\Patrycjusz.Szydlo\AppData\Roaming\npm\node_modules\@lhci\cli\src\collect\puppeteer-manager.js:55:32)
    at Object.runCommand (C:\Users\Patrycjusz.Szydlo\AppData\Roaming\npm\node_modules\@lhci\cli\src\collect\collect.js:147:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
```

Looks like someone has forget about dependency :) 

I can prepare PR if ya like.

PS

**Comment by patrickhulce** [comment]
@pats are you using the new `--puppeteer-script` option?

If you are, `lhci` uses *your* puppeteer version as it's assumed that you're already using puppeteer to do some sort of login. Including puppeteer as a dependency would include a lot of unnecessary postinstall work by default for folks who don't need it. We'll make this clearer in the docs to add puppeteer as a dependency when using `--puppeteer-script` 👍
