### ISSUE TITLE
Error: Cannot find module '@lhci/server' is occurred when running the command lhci server

### ISSUE THREAD

**Issue by KiselevK** [GoogleChrome/lighthouse-ci#255]
Hello!
When I am trying to run **lhci server** I get

`Error: Cannot find module '@lhci/server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.runCommand (/usr/local/lib/node_modules/@lhci/cli/src/server/server.js:60:26)
    at run (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:100:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:119:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32) `

The system is Ubuntu 18.04
It's vm on azure. 

![image](https://user-images.githubusercontent.com/26116730/77371854-ec811700-6d6c-11ea-97a3-ef2f22cf3c9d.png)

**Comment by patrickhulce** [comment]
Thanks for filing! How did you install the Lighthouse CI CLI? `@lhci/server` is an optional dependency (though not officially declared) that needs to be installed alongside wherever the `@lhci/cli` was installed.

If it was global then `@lhci/server` will need to be global too along with a server backend (though it's designed to be installed locally in a `package.json` and will probably be much smoother then.

You might also consider running the prepackaged [docker server](https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/docker-server) :)

**Comment by KiselevK** [comment]
Ohh, Thanks a lot, I missed it...
Docker server works perfect, just want to set up it locally

**Comment by patrickhulce** [comment]
Great glad it's working for you!
