### ISSUE TITLE
Travis only intermittent build ambiguity error

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#260]
On more than one occasion we've had a travis failure for the mysql server test on ambiguous build prefix  resolution. I ran the mysql-server-test suite 1000 times locally without any such failure, so it must be something related to weaker hardware. I'm just collecting the various failures we see now to see if there's any pattern.

**Comment by patrickhulce** [comment]
https://travis-ci.org/github/GoogleChrome/lighthouse-ci/jobs/666863446#L456

```
Summary of all failing tests
FAIL packages/server/test/mysql-server.test.js
  ● mysql server › /:projectId/builds › should handle partial id ambiguity
    expect(received).toEqual(expected) // deep equality
    Expected: undefined
    Received: {"ancestorCommittedAt": "2020-03-25T16:25:15.969Z", "ancestorHash": "0ed0fdcfdce0acdd5eb2508498be50cc55c696ea", "author": "Patrick Hulce <patrick@example.com>", "avatarUrl": "https://avatars1.githubusercontent.com/u/2301202?s=460&v=4", "branch": "master", "commitMessage": "feat: add some awesome features", "committedAt": "2020-03-25T16:25:15.969Z", "createdAt": "2020-03-25T16:25:15.973Z", "externalBuildUrl": "http://travis-ci.org/org/repo/1", "hash": "0.5788507183779821", "id": "00559fbd-2b59-492d-bbde-c629235461fd", "lifecycle": "unsealed", "projectId": "8f4ac345-7626-4eb0-9166-8f687cd2ecb8", "runAt": "2020-03-25T16:25:15.969Z", "updatedAt": "2020-03-25T16:25:16.113Z"}
      327 |       const ambiguousPrefix = findAmbiguity();
      328 |       const buildWithAmbiguousPrefix = builds.find(b => b.id.startsWith(ambiguousPrefix));
    > 329 |       expect(await client.findBuildById(dummyProject.id, ambiguousPrefix)).toEqual(undefined);
          |                                                                            ^
      330 |       expect(await client.findBuildById(dummyProject.id, buildWithAmbiguousPrefix.id)).toEqual(
      331 |         buildWithAmbiguousPrefix
      332 |       );
      at Object.it (packages/server/test/server-test-suite.js:329:76)

```

**Comment by patrickhulce** [comment]
https://travis-ci.org/github/GoogleChrome/lighthouse-ci/jobs/675773728#L383

```
  ● sqlite server (authenticated) › /:projectId/builds › should handle partial id ambiguity
    expect(received).toEqual(expected) // deep equality
    Expected: undefined
    Received: {"ancestorCommittedAt": "2020-04-16T14:30:55.712Z", "ancestorHash": "0ed0fdcfdce0acdd5eb2508498be50cc55c696ea", "author": "Patrick Hulce <patrick@example.com>", "avatarUrl": "https://avatars1.githubusercontent.com/u/2301202?s=460&v=4", "branch": "master", "commitMessage": "feat: add some awesome features", "committedAt": "2020-04-16T14:30:55.712Z", "createdAt": "2020-04-16T14:30:55.720Z", "externalBuildUrl": "http://travis-ci.org/org/repo/1", "hash": "0.3165955334009971", "id": "00197c81-795d-4a7a-90d8-3e85e899a799", "lifecycle": "unsealed", "projectId": "32600e19-6f8c-4b61-a36f-42d368f71426", "runAt": "2020-04-16T14:30:55.712Z", "updatedAt": "2020-04-16T14:30:55.865Z"}
      327 |       const ambiguousPrefix = findAmbiguity();
      328 |       const buildWithAmbiguousPrefix = builds.find(b => b.id.startsWith(ambiguousPrefix));
    > 329 |       expect(await client.findBuildById(dummyProject.id, ambiguousPrefix)).toEqual(undefined);
          |                                                                            ^
      330 |       expect(await client.findBuildById(dummyProject.id, buildWithAmbiguousPrefix.id)).toEqual(
      331 |         buildWithAmbiguousPrefix
      332 |       );
      at Object.it (packages/server/test/server-test-suite.js:329:76)
```

**Comment by patrickhulce** [comment]
pattern so far is that the id begins with `00`, so that's something

**Comment by patrickhulce** [comment]
https://travis-ci.org/github/GoogleChrome/lighthouse-ci/jobs/681680765#L380

```
FAIL packages/server/test/basic-auth-server.test.js (11.214s)
  ● sqlite server (authenticated) › /:projectId/builds › should handle partial id ambiguity
    expect(received).toEqual(expected) // deep equality
    Expected: undefined
    Received: {"ancestorCommittedAt": "2020-04-30T21:12:35.324Z", "ancestorHash": "0ed0fdcfdce0acdd5eb2508498be50cc55c696ea", "author": "Patrick Hulce <patrick@example.com>", "avatarUrl": "https://avatars1.githubusercontent.com/u/2301202?s=460&v=4", "branch": "master", "commitMessage": "feat: add some awesome features", "committedAt": "2020-04-30T21:12:35.324Z", "createdAt": "2020-04-30T21:12:35.330Z", "externalBuildUrl": "http://travis-ci.org/org/repo/1", "hash": "0.4656007588590747", "id": "009b55bd-7bc4-49bb-a620-344c4ace2b8d", "lifecycle": "unsealed", "projectId": "7a5ac8f9-9dd2-4431-b52f-4ffedaf47ca0", "runAt": "2020-04-30T21:12:35.324Z", "updatedAt": "2020-04-30T21:12:35.543Z"}
      327 |       const ambiguousPrefix = findAmbiguity();
      328 |       const buildWithAmbiguousPrefix = builds.find(b => b.id.startsWith(ambiguousPrefix));
    > 329 |       expect(await client.findBuildById(dummyProject.id, ambiguousPrefix)).toEqual(undefined);
          |                                                                            ^
      330 |       expect(await client.findBuildById(dummyProject.id, buildWithAmbiguousPrefix.id)).toEqual(
      331 |         buildWithAmbiguousPrefix
      332 |       );
      at Object.it (packages/server/test/server-test-suite.js:329:76)
```

**Comment by patrickhulce** [comment]
alright triple `00` build IDs that's gotta be it
