### ISSUE TITLE
--puppeteer-script - lhci fails after logging in

### ISSUE THREAD

**Issue by bebraw** [GoogleChrome/lighthouse-ci#300]
I'm currently trying to log in to an app I am developing using the new `--puppeteer-script` feature. Here's my setup:

**package.json**

```json
{
  "scripts": {
    "test:lighthouse": "lhci autorun",
    ...
  },
  ...
}
```

**lighthouserc.json**

```json
{
  "ci": {
    "collect": {
      "staticDistDir": "./build",
      "isSinglePageApplication": true,
      "puppeteerScript": "./scripts/log-in-with-puppeteer.js"
    }
  }
}
```

**scripts/log-in-with-puppeteer.js**

```js
// The script relies on LOGIN_NAME and LOGIN_PASSWORD environment variables
// You can load them either by a dotfile (.env.local) or by setting them in
// the environment.
require('dotenv').config({ path: './.env.local' });

/**
 * @param {puppeteer.Browser} browser
 * @param {{url: string, options: LHCI.CollectCommand.Options}} context
 */
async function main(browser, { url }) {
  const page = await browser.newPage();
  await page.goto(`${new URL(url).origin}/login`);

  await page.waitForSelector('input[name="username"]', { visible: true });

  // Fill in and submit login form.
  const nameInput = await page.$('input[name="username"]');
  await nameInput.type(process.env.LOGIN_NAME);
  const passwordInput = await page.$('input[type="password"]');
  await passwordInput.type(process.env.LOGIN_PASSWORD);

  const submitButton = await page.$('form button');
  await submitButton.click();

  await page.waitForNavigation();
}

module.exports = main;
```

The problem is that once it runs, it gives an error related to multiple tabs:

```bash
 $ yarn run test:lighthouse
yarn run v1.22.4
$ lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
Healthcheck passed!

Started a web server on port 51974...
Running Lighthouse 3 time(s) on http://localhost:51974/index.html
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/shell/node_modules/@lhci/cli/src/collect/lighthouse-runner.js:103:21)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Tue, 05 May 2020 08:02:50 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
Tue, 05 May 2020 08:02:50 GMT status Connecting to browser
Tue, 05 May 2020 08:02:50 GMT status Resetting state with about:blank
Tue, 05 May 2020 08:02:50 GMT status Benchmarking machine
Tue, 05 May 2020 08:02:50 GMT status Initializing…
Tue, 05 May 2020 08:02:50 GMT status Disconnecting from browser...
Runtime error encountered: You probably have multiple tabs open to the same origin.
Error: You probably have multiple tabs open to the same origin.
```

I saw this error before when trying to run Puppeteer and then Lighthouse through it and I found https://github.com/GoogleChrome/lighthouse/issues/3837 which seems related.

Can you see anything obviously wrong in my setup or is this a known issue with lhci as well? I suspect it might be the same problem and might require underlying fixes.

**Comment by patrickhulce** [comment]
Try throwing `await page.close()` at the end of your puppeteer script. Lighthouse from CLI expects the page to not already be open and Lighthouse can't unregister service workers if one is running.

**Comment by bebraw** [comment]
Ok, thanks! That was it. 👍
