### ISSUE TITLE
Feature: Allow for custom sequelize configuration

### ISSUE THREAD

**Issue by cannjeff** [GoogleChrome/lighthouse-ci#327]
Request: Allow for the ability to provide advanced Sequelize configuration.

Example: When using an RDS postgres instance it can take upwards of 30 seconds, or more, for the instance to come online after being paused. The default `pool.acquire` is 10 seconds.
Sequelize Timeout error:
```
::ffff:10.84.1.1 - GET /v1/projects HTTP/1.1 500 609 - 10002.843 ms
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/opt/app-root/src/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/opt/app-root/src/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Proposed solution: https://github.com/GoogleChrome/lighthouse-ci/pull/326

**Comment by patrickhulce** [comment]
fixed by #326
