### ISSUE TITLE
Failing to upload using CircleCI parallel builds

### ISSUE THREAD

**Issue by jflayhart** [GoogleChrome/lighthouse-ci#366]
The following error is occurring I _think_ because it's trying to upload to the same `123abc` hash on different parallel machines.

I NEED to have parallel machines to speed up the lighthouse ci and the first url to finish the test is the only one to be uploaded 😞 

```
Error: Unexpected status code 422
 
  {"message":"Build already exists for hash \"123abc\""}
 
    at ApiClient._convertFetchResponseToReturnValue (/home/circleci/project/node_modules/@****/utils/src/api-client.js:91:21)
 
    at process._tickCallback (internal/process/next_tick.js:68:7)
 
WARNING: upload command failed.
```

**Comment by patrickhulce** [comment]
Hello again @jflayhart thanks for filing :)

In general, this won't work. From the docs...

> NOTE: If you run a matrix of environments in your tests, make sure you only run lhci autorun ONCE per build. The Lighthouse CI server will only accept a single upload per hash and future attempts to upload data for that hash will be rejected.

What you *can* do to parallelize things is run `lhci collect` on separate machines, save the `.lighthouseci` folder as a build artifact, then merge all the folder contents together and run `lhci assert`/`lhci upload` when they're all done.

In principle the server APIs already support partial uploads but there does need to be one final thing that says "ok now we're all done". Some `--partial-upload`/`--finalize-build` pair of flags on the CLI `upload` command would be needed to make this happen, and I'd be open to a PR if anyone wanted to add such functionality 👍

**Comment by jflayhart** [comment]
Ah i [see the docs on this](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#configuration). thanks for the tip, that's what I'll do!

**Comment by richardmtsr** [comment]
Bump on this - we would like to audit urls on a daily basis using a schedule so we can see fluctuations in our performance over time. With duplicate builds for the same commit not being allowed this doesn't seem possible - any ideas on how we get around this?

**Comment by mikeapr4** [comment]
If anyone else needs this, there is a build hash override environment variable LHCI_BUILD_CONTEXT__GIT_REMOTE

I'm using Gitlab CI so I set it to the job ID:
`LHCI_BUILD_CONTEXT__GIT_REMOTE=$CI_JOB_ID lhci autorun`

**Comment by harrydevane** [comment]
We would also find support for uploading the same build hash twice useful, if we have a build pipeline step fail after lighthouse CI has uploaded we cannot restart the build without amending the commit to change the hash or we get the `Build already exists for hash` error
