### ISSUE TITLE
Invalid token issues

### ISSUE THREAD

**Issue by amcarthur** [GoogleChrome/lighthouse-ci#401]
Hi, I'm having trouble setting the build token for autorun. I'm trying to not set the token in the config file obviously so that the token is not in the Git repo.

My config file looks like:
```
{
  "ci": {
    "collect": {
      "settings": {
        "chromeFlags": "--no-sandbox"
      },
      "url": [
        "https://<some url>/",
        "https://<some url>"
      ]
    },
    "assert": {
      "assertions": {
        "categories:performance": [
          "warn",
          {
            "minScore": 0.8
          }
        ],
        "categories:accessibility": [
          "warn",
          {
            "minScore": 0.8
          }
        ],
        "categories:best-practices": [
          "warn",
          {
            "minScore": 0.8
          }
        ],
        "categories:seo": [
          "warn",
          {
            "minScore": 0.8
          }
        ]
      }
    },
    "upload": {
      "target": "lhci",
      "serverBaseUrl": "https://<my lighthouse server>/"
    }
  }
}
```

I have tried setting it in the command line arguments like so:
`lhci autorun --basicAuth.username=<myusername> --basicAuth.password=<mypass> --token=<my token>`

I get this error during the upload step (the healthcheck passes):
```
All results processed!
Error: Must provide token for LHCI target
    at runLHCITarget (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:382:29)
    at Object.runCommand (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:581:22)
    at run (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:92:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:120:1)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47WARNING: upload command failed.
```

I have also tried setting the LHCI_TOKEN env variable, and I get this error during the healthcheck:
```
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  Ancestor hash determinable
⚠️   LHCI server not reachable
⚠️   LHCI server not API-compatible
⚠️   LHCI server token invalid
    ERROR: Unexpected status code 401
  
⚠️   LHCI server non-unique build for this hash
    ERROR: Unexpected status code 401
  
Healthcheck passed!
```

What am I doing wrong?

**Comment by patrickhulce** [comment]
If you're using CLI flags *with autorun* then you need to prefix each option for the command that uses it.

i.e.

`lhci autorun --upload.token=THE_TOKEN`

The same goes for `--upload.basicAuth.username` (which is why I'm guessing it didn't work with your env variable.

That said I would recommend doing all of this inside a config file.

```js
module.exports = {
  ci: {
    upload: {
      token: process.env.THE_TOKEN,
      basicAuth: {username: process.env.THE_USERNAME, password: process.env.THE_PASSWORD}
    }
  }
}

**Comment by amcarthur** [comment]
Thanks @patrickhulce I believe that fixed my problems. I know it's unrelated, I can make a new issue if you want, but I'm sure it's just my own stupidty: I'm now getting an error "Unable to automatically determine the location of static site files.". I was under the impression you could specify URL's of remote URL's already deployed instead of static html files or starting a local server. Do you see anything wrong with my config:
```
module.exports = {
  ci: {
    collect: {
      settings: {
        chromeFlags: "--no-sandbox"
      },
      url: ["https://<some remote url>/", "<another remote url>"]
    },
    assert: {
      preset: "lighthouse:recommended"
    },
    upload: {
      serverBaseUrl: "<my server lighthouse url>",
      token: process.env.LIGHTHOUSE_BUILD_TOKEN,
      basicAuth: {username: process.env.LIGHTHOUSE_AUTH_USER, password: process.env.LIGHTHOUSE_AUTH_PASSWORD}
    }
  }
};
```

**Comment by patrickhulce** [comment]
Everything seems fine in that file. The new config file you created probably isn't getting processed correctly because you can't run into the token problem until *after* the URLs are collected so this is a much earlier problem. 

Is it passing the "Configuration found" healthcheck? Did you name the file to `lighthouserc.js` and it's still in the CWD?
