### ISSUE TITLE
Upload results to Lighthouse CI server

### ISSUE THREAD

**Issue by rhyst** [GoogleChrome/lighthouse-ci#486]
I am generating lighthouse reports programatically (due to a complicated deployment/login process) and I can generate html or json result files.

How do I upload these to a lighthouse CI server?

I have started a Lighthouse CI server locally using a docker image:

```
docker container run --publish 9001:9001 --mount='source=lhci-data,target=/data' --detach patrickhulce/lhci-server
```

And set it up using the wizard:

```
lhci wizard
```

If I navigate to `localhost:9001` I can see the empty project.

From the root of my repository I am trying to run:

```
lhci upload --token <some-token>
```

The first time I run this I get the following error:

```
Error: Unexpected status code 422
  {"message":"Invalid build"}
    at ApiClient._convertFetchResponseToReturnValue (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:78:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runLHCITarget (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/src/upload/upload.js:454:3)
    at async Object.runCommand (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/src/upload/upload.js:594:16)
    at async run (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/src/cli.js:92:7)%           
```

And despite this failure subsequent attempts fail with a different error about duplicate builds:

```
Error: Unexpected status code 422
  {"message":"Build already exists for hash \"2ebc51dd2d9dc977b3e7a02ba28f127a6d6c4b62\""}
    at ApiClient._convertFetchResponseToReturnValue (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:78:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runLHCITarget (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/src/upload/upload.js:411:17)
    at async Object.runCommand (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/src/upload/upload.js:594:16)
    at async run (~/.asdf/installs/nodejs/14.5.0/.npm/lib/node_modules/@lhci/cli/src/cli.js:92:7)%  
```

Navigating to `localhost:9001`reveals it is still empty.

I can't find anything in the documentation that says how to configure which reports to upload. This seemed to create a `.lighthouseci` folder in my repo so I tried placing the json and html reports in there but this didn't change anything.

Thanks for any help.

**Comment by patrickhulce** [comment]
Thanks for filing @rhyst!

> How do I upload these to a lighthouse CI server?

You can hit the API directly or match the way the `collect` command stores the reports.

> I can't find anything in the documentation that says how to configure which reports to upload

That's because you're not really meant to manually upload yourself via the CLI :)

> This seemed to create a .lighthouseci folder in my repo so I tried placing the json and html reports in there but this didn't change anything.

Did you name them `lhr-<any number>.json` and `lhr-<any number>.html`?

**Comment by rhyst** [comment]
Ah yeh I've got something working now by basically copying what is in [the cli package uploade stuff](https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/cli/src/upload/upload.js). Good to know that I've not missed anything easier though.

(I did not follow that naming convention so that was probably what was going wrong with uploading using the cli tool)

**Comment by patrickhulce** [comment]
Glad you got it sorted out!

**Comment by pillsilly** [comment]
> Ah yeh I've got something working now by basically copying what is in [the cli package uploade stuff](https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/cli/src/upload/upload.js). Good to know that I've not missed anything easier though.
> 
> (I did not follow that naming convention so that was probably what was going wrong with uploading using the cli tool)

HI @rhyst 
could you introduce how you resolve the problem? 
What kind of naming convection there you had used at last?
I tried what's mentioned the `lhr-<any number>.json` but it didn't work.
