### ISSUE TITLE
failed loading plugins in `node_modules`

### ISSUE THREAD

**Issue by koh110** [GoogleChrome/lighthouse-ci#492]
I'm having trouble `lhci collect` with plugins is failed.

https://github.com/GoogleChrome/lighthouse#plugins
https://github.com/treosh/lighthouse-plugin-field-performance

```bash
$ which lhci
/usr/local/bin/lhci
$ lhci --version
0.6.1
$ pwd
/home/koh110/dev/tmp/lighthouse-test
$ cat package.json 
{
  "private": true,
  "dependencies": {
    "lighthouse-plugin-field-performance": "^2.2.1"
  }
}
$ ls -la
total 112
drwxrwxr-x   3 koh110 koh110  4096 11月 15 17:11 ./
drwxrwxr-x  17 koh110 koh110  4096 11月 14 19:34 ../
-rw-rw-r--   1 koh110 koh110   137 11月 14 17:18 lighthouse.js
drwxrwxr-x 224 koh110 koh110 12288 11月 14 19:28 node_modules/
-rw-rw-r--   1 koh110 koh110   127 11月 14 19:28 package.json
-rw-rw-r--   1 koh110 koh110 74807 11月 14 19:28 package-lock.json

$ lhci collect --url=https://google.com --config=./lighthouse.js 
Running Lighthouse 3 time(s) on https://google.com
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:119:21)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

Runtime error encountered: Unable to locate plugin: `lighthouse-plugin-field-performance`.
     Tried to require() from these locations:
       /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config
       /home/koh110/dev/tmp/lighthouse-test/lighthouse-plugin-field-performance
       /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/lighthouse-plugin-field-performance
Error: Unable to locate plugin: `lighthouse-plugin-field-performance`.
     Tried to require() from these locations:
       /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config
       /home/koh110/dev/tmp/lighthouse-test/lighthouse-plugin-field-performance
       /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/lighthouse-plugin-field-performance
    at resolveModule (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:213:9)
    at Function.mergePlugins (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config.js:444:9)
    at new Config (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config.js:335:25)
    at generateConfig (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/index.js:60:10)
    at lighthouse (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/index.js:43:18)
    at runLighthouse (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/run.js:224:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

# Cause

This seems to be due to the `resolveModule` in `lighthouse-core`.

https://github.com/GoogleChrome/lighthouse/blob/378a31f8117d20c852562514612c80ea12892c54/lighthouse-core/config/config-helpers.js#L178

In my case, I would expect the plugin to be loaded under SECOND condition.

`lhci` is installed in global and plugin exists in current working directory.

# Solution

I think `resolveModule` should be coded like this.
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

```diff
   // then the config is an object and so has no path.
-   const cwdPath = path.resolve(process.cwd(), moduleIdentifier);
   try {
-    return require.resolve(cwdPath);
+    return require.resolve(moduleIdentifier, { paths: [process.cwd()]});
   } catch (e) {}
```

If I'm right, this is not `lhci` problem. I think I will send a PR to `lighthouse-core`, is this correct?

I followed the code and it appears since 2016.
https://github.com/GoogleChrome/lighthouse/pull/679

So I couldn't determine if this was a bug or a specification.

**Comment by patrickhulce** [comment]
Thanks for filing @koh110! You're right this is a lighthouse-core problem with resolution of plugins when lighthouse is globally installed (like in this example). I'll go ahead and transfer this issue :)
