### ISSUE TITLE
Error thrown by lighthouse 'lhci wizard' for new-project option is not fully describing the actual issue

### ISSUE THREAD

**Issue by LokeshNSF** [GoogleChrome/lighthouse-ci#516]
**Describe the bug**
When trying to create a new-project using lhci wizard, the error thrown by it was not fully describing the issue.
In this case, the database write access to the tables were blocked in postgres and the error thrown by the lhci wizard command is,
Error: Unexpected status code 500
  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (/Users/lokeshkumar.n/.volta/tools/image/packages/@lhci/cli/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:78:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

The error above doesn't fully describe the issue on the client side.
When I see the server logs, actual problem is shown as,
 SequelizeDatabaseError: permission denied for table projects

**To Reproduce**
1. Go to postgres db and remove the write access permission on the tables used by lhci server.
2. Install lhci cli and run the command lhci wizard and provide the options to create a new-project.
3. See the error as mentioned above - 500 Internal server error.

**Expected behavior**
Cli should clearly mention the error caused due to permission issue in db table.

**Logs/Screenshots**
Error logs attached in the description.

**Environment (please complete the following information):**
 - OS: MacOS
 - Cli
 - Version - 0.5.1

**Additional context**
N/A

**Comment by patrickhulce** [comment]
Thanks for filing @LokeshNSF! This is intentional behavior to not expose internal server details in error messages that are (probably) publicly accessible. I understand it must have been confusing to know where to look though. Would the CLI printing "Internal Server Error - Check your LHCI server logs for more details" been more helpful?

**Comment by LokeshNSF** [comment]
> Thanks for filing @LokeshNSF! This is intentional behavior to not expose internal server details in error messages that are (probably) publicly accessible. I understand it must have been confusing to know where to look though. Would the CLI printing "Internal Server Error - Check your LHCI server logs for more details" been more helpful?

Changing the error message would help. Thanks.
