### ISSUE TITLE
first time using Node-red  this error happened

### ISSUE THREAD

**Issue by mimocaty** [GoogleChrome/lighthouse-ci#615]
Dears,

please ur help is highly appriciated 
ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
23 May 11:18:11 - [red] Uncaught Exception:
23 May 11:18:11 - RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received .
    at new NodeError (node:internal/errors:363:5)
    at validatePort (node:internal/validators:208:11)
    at lookupAndConnect (node:net:987:5)
    at Socket.connect (node:net:963:5)
    at Object.connect (node:net:192:17)
    at NodeS7.connectNow (C:\Users\mabde\.node-red\node_modules\nodes7\nodeS7.js:163:30)
    at NodeS7.initiateConnection (C:\Users\mabde\.node-red\node_modules\nodes7\nodeS7.js:129:7)
    at connectNow (C:\Users\mabde\.node-red\node_modules\industrialcomm\s7comm.js:642:16)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by patrickhulce** [comment]
Please fill out the entirety of [an issue template](https://github.com/GoogleChrome/lighthouse-ci/tree/main/.github/ISSUE_TEMPLATE) with reproduction steps for us to be able to help. Also see https://github.com/GoogleChrome/lighthouse-ci/issues/258 which has already discussed this exact error message at length.
