### ISSUE TITLE
Could not find active project with provided token

### ISSUE THREAD

**Issue by poteirard** [GoogleChrome/lighthouse-ci#641]
**Describe the bug**
I'm trying to collect LH reports in my self-hosted github/jenkins

But I get the error:

```
14:26:30  Error: Could not find active project with provided token
14:26:30      at runLHCITarget (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:401:11)
14:26:30      at processTicksAndRejections (internal/process/task_queues.js:93:5)
14:26:30      at async Object.runCommand (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:592:16)
14:26:30      at async run (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:109:7)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. I create PR
2. I get the error in the pipeline

**Expected behaviour**
Not having an error or at least to show a better log experience 

**Logs/Screenshots**

<img width="1233" alt="Notification_Center" src="https://user-images.githubusercontent.com/7198934/123816149-5cc70280-d8f7-11eb-9626-c96f6c7ffebe.png">

lighthouserc.js

```js
module.exports = {
  ci: {
    collect: {
      numberOfRuns: 1,
      puppeteerScript: './puppeteer-script.js',
      url: [
        'http://web-dashboard.dev.local:3000/test/web',
      ],
      startServerCommand: 'node -r dotenv/config dist/index.js',
      puppeteerLaunchOptions: {
        args: ['--no-sandbox', '--disable-web-security', '--disable-extensions', '--incognito'],
      },
    },
    upload: {
      target: 'lhci',
      serverBaseUrl: 'https://lighthouse-ci.eks-uat.my-company',
      token: 'eff17e20-5117-451c-ac54-21b4b4d1f693', // taken from running npx @lhci/cli wizard
    },
  },
};
```

Env vars:

```
env.LHCI_BUILD_CONTEXT__COMMIT_MESSAGE = sh (script: 'git log -1 --pretty=%B ${GIT_COMMIT}', returnStdout: true).trim()
LHCI_GITHUB_TOKEN = "<my token>"
LHCI_BUILD_CONTEXT__CURRENT_BRANCH = "${env.BRANCH_NAME}"
LHCI_BUILD_CONTEXT__CURRENT_HASH = "${env.GIT_COMMIT}"
LHCI_BUILD_CONTEXT__COMMIT_MESSAGE = "${env.GIT_COMMIT}"
LHCI_TOKEN = "eff17e20-5117-451c-ac54-21b4b4d1f693" # taken from running npx @lhci/cli wizard. Same as in config, I tried both ways in separate
```

**Environment (please complete the following information):**
 - OS: Custom docker image
 - Browser chrome
 - Version latest

**Additional context**
- We are using Github Enterprise
- Custom Jenkins
- K8s Eks cluster for the webs 
- Private network
- The lhci server is running with sqlite db

```js
import {createServer} from "@lhci/server";

console.log('Starting server...');
createServer({
    port: process.env.PORT || 8080,
    storage: {
        storageMethod: 'sql',
        sqlDialect: 'sqlite',
        sqlDatabasePath: './data/db.sql',
    },
}).then(({port}) => console.log('Lighthouse CI listening on port', port));
```

**Comment by patrickhulce** [comment]
Thanks for filing @poteirard! These messages suggest that the `LHCI_TOKEN` environment variable and the `upload.token` property in the config do not match or are invalid.

**Comment by poteirard** [comment]
Thanks, @patrickhulce for the fast response.

Unfortunately, I have tried to run it with all the different combinations (env and config) and still get the same error.

I saw in another issue that I could curl the token to check if it's correct and I did it:

```bash
curl -X POST -H 'Content-Type: application/json' -d '{"token": "eff17e20-5117-451c-ac54-21b4b4d1f693"}' https://lighthouse-ci.selfserve.eks-uat.zopa/v1/projects/lookup

{"id":"f62049bd-c036-4826-8b9d-ea892613d2da","name":"web-dashboard","slug":"web-dashboard","externalUrl":"https://github.dns.ad.zopa.com/foo/web-dashboard","token":"eff17e20-5117-451c-ac54-21b4b4d1f693","baseBranch":"master","adminToken":"","createdAt":"2021-06-29T11:04:37.143Z","updatedAt":"2021-06-29T11:18:06.737Z"}%
```

**Comment by poteirard** [comment]
Ok, I think I found the issue I had 2 replicas in k8s, so sometimes it was reading the sqlite db and sometimes it doesn't. I hope it helps for someone else
