### ISSUE TITLE
Cannot find module 'csp_evaluator/dist/lighthouse/lighthouse_checks.js' when running lhci collect

### ISSUE THREAD

**Issue by dkarzon** [GoogleChrome/lighthouse-ci#664]
**Describe the bug**
Error when trying to run lhci collect. I am using Bitbucket Pipelines to run a daily build and the most recent run has started to fail with the error `Cannot find module 'csp_evaluator/dist/lighthouse/lighthouse_checks.js'`. No changes have been made on my end with the configuration or the infrastructure.
I can also reproduce this error locally (on both Windows and Linux).
There was a recent update to the lighthouse dependency but I can't tell if that was the cause or not, the timing aligns with when I started seeing the issue though https://www.npmjs.com/package/lighthouse

**To Reproduce**
1. Run `npm install -g @lhci/cli@0.8.0`
2. Run `lhci collect` using the below config
3. See error

Example lighthouserc.yaml
```
ci:
    collect:
        url:
        - https://google.com/
```

**Expected behavior**

**Logs/Screenshots**
The full error log:
```
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
Wed, 04 Aug 2021 14:55:07 GMT ChromeLauncher Waiting for browser.
Wed, 04 Aug 2021 14:55:07 GMT ChromeLauncher Waiting for browser...
Wed, 04 Aug 2021 14:55:08 GMT ChromeLauncher Waiting for browser.....
Wed, 04 Aug 2021 14:55:08 GMT ChromeLauncher Waiting for browser.....✓
Wed, 04 Aug 2021 14:55:08 GMT ChromeLauncher Killing Chrome instance 6419
(node:6403) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Runtime error encountered: Cannot find module 'csp_evaluator/dist/lighthouse/lighthouse_checks.js'
Require stack:
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/lib/csp-evaluator.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/audits/csp-xss.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config-helpers.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/index.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/commands/list-audits.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/commands/commands.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/bin.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/index.js
Error: Cannot find module 'csp_evaluator/dist/lighthouse/lighthouse_checks.js'
Require stack:
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/lib/csp-evaluator.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/audits/csp-xss.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config-helpers.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/config/config.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/index.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/commands/list-audits.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/commands/commands.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/bin.js
- /usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-cli/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/lib/csp-evaluator.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Environment (please complete the following information):**
Local
 - OS: Windows
 - Browser: Chrome
 - Version: 92

CI Build
- Image: node:16-buster-slim

**Comment by patrickhulce** [comment]
Thanks for filing! See https://github.com/GoogleChrome/lighthouse-ci/issues/662
