### ISSUE TITLE
Heroku recipe setup results in a app that crashes

### ISSUE THREAD

**Issue by florin-tomozei-wpd** [GoogleChrome/lighthouse-ci#672]
**Describe the bug**
Followed the exact instructions indicated in the Heroku Recipe here
https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/recipes/heroku-server/README.md

getting the following error:
```
2021-08-16T14:07:50.853683+00:00 app[web.1]: Starting server...
2021-08-16T14:07:51.060836+00:00 app[web.1]: (node:22) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.
2021-08-16T14:07:51.069127+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: SequelizeConnectionError: self signed certificate
2021-08-16T14:07:51.069129+00:00 app[web.1]: at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:154:24
2021-08-16T14:07:51.069129+00:00 app[web.1]: at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:194:14)
2021-08-16T14:07:51.069130+00:00 app[web.1]: at Connection.emit (events.js:314:20)
2021-08-16T14:07:51.069130+00:00 app[web.1]: at TLSSocket.reportStreamError (/app/node_modules/pg/lib/connection.js:73:10)
2021-08-16T14:07:51.069131+00:00 app[web.1]: at TLSSocket.emit (events.js:314:20)
2021-08-16T14:07:51.069131+00:00 app[web.1]: at emitErrorNT (internal/streams/destroy.js:92:8)
2021-08-16T14:07:51.069132+00:00 app[web.1]: at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2021-08-16T14:07:51.069132+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-16T14:07:51.069178+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-08-16T14:07:51.069209+00:00 app[web.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-08-16T14:07:51.132937+00:00 heroku[web.1]: Process exited with status 0
2021-08-16T14:07:51.194039+00:00 heroku[web.1]: State changed from starting to crashed
2021-08-16T14:08:05.590233+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-chamber-00637.herokuapp.com request_id=68018b9d-1dae-43e8-a2c7-c13e37aa63d7 fwd="78.96.158.101" dyno= connect= service= status=503 bytes= protocol=https
2021-08-16T14:08:05.921950+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=tranquil-chamber-00637.herokuapp.com request_id=890c0ce2-bca4-4f90-ab21-7e8c33ea8b7d fwd="78.96.158.101" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by patrickhulce** [comment]
Thanks for filing @florin-tomozei-wpd!

That error is indicating the SQL connection is using a self-signed cert not backed by a CA. Heroku should not be assigning you such a cert (there aren't for us and I can't remember anyone filing a similar issue :/), but if they are and you don't care you can try adding `rejectUnauthorized` to the `server.sqlDialectOptions.ssl` object.

**Comment by florin-tomozei-wpd** [comment]
@patrickhulce confirming that setting that inside the server.js storage configuration worked.

solution is to set inside server.js the following:

```
sqlDialectOptions: {
  ssl: {
    rejectUnauthorized: false
  }
},
```

**Comment by sarunast** [comment]
@patrickhulce FYI> I was trying to set up heroku instance as well and I had in the end same issue.

**Comment by la55u** [comment]
same issue following the exact steps from the lhci heroku setup guide

**Comment by patrickhulce** [comment]
thanks @sarunast @la55u I updated the recipe with the fix 👍  See https://github.com/GoogleChrome/lighthouse-ci/commit/4c034667339d6117ac77c663a53892757a29d750
