### ISSUE TITLE
lhci assert "Error: No assertions to use" error

### ISSUE THREAD

**Issue by PhilDye** [GoogleChrome/lighthouse-ci#747]
**Describe the bug**
Running with a bare-bones config results in "Error: No assertions to use"

**To Reproduce**
1. Use the following lighthouserc.js;
```
module.exports = {
    ci: {
        collect: {
            numberOfRuns: 1,
            url: [
                "https://www.REDACTED.com/",
            ]
        }
    },
    assert: {
        preset: "lighthouse:no-pwa"
    },
    upload: {
        target: "temporary-public-storage"
    }
};

```
2. Run `lhci collect`
3. Verify files present in .lighthouserci folder, including `assertion-results.json`
3. Run `lhci assert`

**Expected behavior**
Assertion output (passed/failed as appropriate) to console.

**Logs/Screenshots**
```
> lhci collect
Running Lighthouse 1 time(s) on https://www.REDACTED.com/
Run #1...done.
Done running Lighthouse!
> lhci assert
Error: No assertions to use
    at Object.runCommand (/usr/local/lib/node_modules/@lhci/cli/src/assert/assert.js:51:48)
    at run (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:106:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:137:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47%   
```

**Environment (please complete the following information):**
 - OS: macOS Montererey 12.0.1
 - Browser: Chrome 97
 - lhci version: 0.8.2
 - node version: 14.18.3

**Additional context**
Problem was initially observed with a much larger config file, but I've progressively stripped this back. `lhci autorun`, with the same config file present, completes as expected;

```
> lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
Healthcheck passed!

Running Lighthouse 1 time(s) on https://www.REDACTED.com/
Run #1...done.
Done running Lighthouse!

Checking assertions against 1 URL(s), 1 total run(s)

30 result(s) for https://www.REDACTED.com/ :

  ✘  button-name failure for minScore assertion
       Buttons do not have an accessible name
       https://web.dev/button-name/

        expected: >=0.9
           found: 0
      all values: 0


  ✘  color-contrast failure for minScore assertion
(etc)
```

**Comment by PhilDye** [comment]
Doh! `assert` and `upload` should be within the `ci` block - how many hours was I staring at this?!
