### ISSUE TITLE
LHCI doesn't connect to Chrome on WSL2

### ISSUE THREAD

**Issue by mferuscomelo** [GoogleChrome/lighthouse-ci#761]
**Describe the bug**
I'm using WSL2 on Windows 11 to develop my Hugo-based website. After completing a production build, I executed the command `lhci autorun` got the error that LHCI wasn't able to connect to Chrome. Please refer to the logs below for more information. 

I've set up WSLg and executing `google-chrome` works as expected. After the test has started, navigating to `http://localhost:34525/` in Chrome on Windows as well as executing `curl http://localhost:34525/` works as expected and returns the webpage. I've also tried visiting the site on Chrome through WSLg, which has also worked perfectly. 

What could be causing the problem? Thanks in advance and please let me know if I should provide further information. 

**Logs/Screenshots**
```
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
⚠️   GitHub token not set
Healthcheck passed!

Started a web server on port 34525...
Running Lighthouse 3 time(s) on http://localhost:34525/404.html
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/home/milanfc/.nvm/versions/node/v14.17.2/lib/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Mon, 14 Feb 2022 16:59:11 GMT LH:ChromeLauncher Waiting for browser.
Mon, 14 Feb 2022 16:59:11 GMT LH:ChromeLauncher Waiting for browser...
Mon, 14 Feb 2022 16:59:12 GMT LH:ChromeLauncher Waiting for browser.....
Mon, 14 Feb 2022 16:59:12 GMT LH:ChromeLauncher Waiting for browser.......
Mon, 14 Feb 2022 16:59:13 GMT LH:ChromeLauncher Waiting for browser.........
Mon, 14 Feb 2022 16:59:13 GMT LH:ChromeLauncher Waiting for browser...........
Mon, 14 Feb 2022 16:59:14 GMT LH:ChromeLauncher Waiting for browser.............
Mon, 14 Feb 2022 16:59:14 GMT LH:ChromeLauncher Waiting for browser...............
Mon, 14 Feb 2022 16:59:15 GMT LH:ChromeLauncher Waiting for browser.................
Mon, 14 Feb 2022 16:59:15 GMT LH:ChromeLauncher Waiting for browser...................
Mon, 14 Feb 2022 16:59:16 GMT LH:ChromeLauncher Waiting for browser.....................
Mon, 14 Feb 2022 16:59:16 GMT LH:ChromeLauncher Waiting for browser.......................
Mon, 14 Feb 2022 16:59:17 GMT LH:ChromeLauncher Waiting for browser.........................
Mon, 14 Feb 2022 16:59:17 GMT LH:ChromeLauncher Waiting for browser...........................
Mon, 14 Feb 2022 16:59:18 GMT LH:ChromeLauncher Waiting for browser.............................
Mon, 14 Feb 2022 16:59:18 GMT LH:ChromeLauncher Waiting for browser...............................
Mon, 14 Feb 2022 16:59:19 GMT LH:ChromeLauncher Waiting for browser.................................
Mon, 14 Feb 2022 16:59:19 GMT LH:ChromeLauncher Waiting for browser...................................
Mon, 14 Feb 2022 16:59:20 GMT LH:ChromeLauncher Waiting for browser.....................................
Mon, 14 Feb 2022 16:59:20 GMT LH:ChromeLauncher Waiting for browser.......................................
Mon, 14 Feb 2022 16:59:21 GMT LH:ChromeLauncher Waiting for browser.........................................
Mon, 14 Feb 2022 16:59:21 GMT LH:ChromeLauncher Waiting for browser...........................................
Mon, 14 Feb 2022 16:59:22 GMT LH:ChromeLauncher Waiting for browser.............................................
Mon, 14 Feb 2022 16:59:22 GMT LH:ChromeLauncher Waiting for browser...............................................
Mon, 14 Feb 2022 16:59:23 GMT LH:ChromeLauncher Waiting for browser.................................................
Mon, 14 Feb 2022 16:59:23 GMT LH:ChromeLauncher Waiting for browser...................................................
Mon, 14 Feb 2022 16:59:24 GMT LH:ChromeLauncher Waiting for browser.....................................................
Mon, 14 Feb 2022 16:59:24 GMT LH:ChromeLauncher Waiting for browser.......................................................
Mon, 14 Feb 2022 16:59:25 GMT LH:ChromeLauncher Waiting for browser.........................................................
Mon, 14 Feb 2022 16:59:25 GMT LH:ChromeLauncher Waiting for browser...........................................................
Mon, 14 Feb 2022 16:59:26 GMT LH:ChromeLauncher Waiting for browser.............................................................
Mon, 14 Feb 2022 16:59:26 GMT LH:ChromeLauncher Waiting for browser...............................................................
Mon, 14 Feb 2022 16:59:27 GMT LH:ChromeLauncher Waiting for browser.................................................................
Mon, 14 Feb 2022 16:59:27 GMT LH:ChromeLauncher Waiting for browser...................................................................
Mon, 14 Feb 2022 16:59:28 GMT LH:ChromeLauncher Waiting for browser.....................................................................
Mon, 14 Feb 2022 16:59:28 GMT LH:ChromeLauncher Waiting for browser.......................................................................
Mon, 14 Feb 2022 16:59:29 GMT LH:ChromeLauncher Waiting for browser.........................................................................
Mon, 14 Feb 2022 16:59:29 GMT LH:ChromeLauncher Waiting for browser...........................................................................
Mon, 14 Feb 2022 16:59:30 GMT LH:ChromeLauncher Waiting for browser.............................................................................
Mon, 14 Feb 2022 16:59:30 GMT LH:ChromeLauncher Waiting for browser...............................................................................
Mon, 14 Feb 2022 16:59:31 GMT LH:ChromeLauncher Waiting for browser.................................................................................
Mon, 14 Feb 2022 16:59:31 GMT LH:ChromeLauncher Waiting for browser...................................................................................
Mon, 14 Feb 2022 16:59:32 GMT LH:ChromeLauncher Waiting for browser.....................................................................................
Mon, 14 Feb 2022 16:59:32 GMT LH:ChromeLauncher Waiting for browser.......................................................................................
Mon, 14 Feb 2022 16:59:33 GMT LH:ChromeLauncher Waiting for browser.........................................................................................
Mon, 14 Feb 2022 16:59:33 GMT LH:ChromeLauncher Waiting for browser...........................................................................................
Mon, 14 Feb 2022 16:59:34 GMT LH:ChromeLauncher Waiting for browser.............................................................................................
Mon, 14 Feb 2022 16:59:34 GMT LH:ChromeLauncher Waiting for browser...............................................................................................
Mon, 14 Feb 2022 16:59:35 GMT LH:ChromeLauncher Waiting for browser.................................................................................................
Mon, 14 Feb 2022 16:59:35 GMT LH:ChromeLauncher Waiting for browser...................................................................................................
Mon, 14 Feb 2022 16:59:36 GMT LH:ChromeLauncher Waiting for browser.....................................................................................................
Mon, 14 Feb 2022 16:59:36 GMT LH:ChromeLauncher Waiting for browser.......................................................................................................
Mon, 14 Feb 2022 16:59:36 GMT LH:ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:40213
Mon, 14 Feb 2022 16:59:36 GMT LH:ChromeLauncher:error Logging contents of /mnt/c/Users/milanfc/AppData/Local/lighthouse.94971075/chrome-err.log
Mon, 14 Feb 2022 16:59:36 GMT LH:ChromeLauncher:error 
DevTools listening on ws://127.0.0.1:40213/devtools/browser/507c23fe-52b5-4d0a-905c-67f4e1597cf3

Unable to connect to Chrome
```

**Environment (please complete the following information):**
 - Windows 11 Version 21H2 OS Build 22000.493
 - Chrome

**Comment by SilverLinings89** [comment]
Same issue for me

**Comment by MichelAraujo** [comment]
Sama issue for me

**Comment by enots227** [comment]
Here is a workaround:

1. Install Chrome within the WSL environment https://askubuntu.com/a/79284
2. Set lhci configuration to point to WSL Chrome install.

**lighthouserc.js**
```
module.exports = {
  ci: {
    collect: {
      chromePath: '/usr/bin/google-chrome',
    },
  },
};
```
I am getting an issue where it creates AppData folders in the root of my project that I still need to figure out.

**Comment by gmferland** [comment]
> Here is a workaround:
> 
> 1. Install Chrome within the WSL environment https://askubuntu.com/a/79284
> 2. Set lhci configuration to point to WSL Chrome install.
> 
> **lighthouserc.js**
> 
> ```
> module.exports = {
>   ci: {
>     collect: {
>       chromePath: '/usr/bin/google-chrome',
>     },
>   },
> };
> ```
> 
> I am getting an issue where it creates AppData folders in the root of my project that I still need to figure out.

I experienced the same issue with the AppData folders in my project. Eventually I found this code block in the `chrome-launcher` package that would explain that behavior.
```javascript
// chrome-launcher/dist/chrome-launcher.js
if (!this.useDefaultProfile) {
    // Place Chrome profile in a custom location we'll rm -rf later
    // If in WSL, we need to use the Windows format
    flags.push(`--user-data-dir=${isWsl ? utils_1.toWinDirFormat(this.userDataDir) : this.userDataDir}`);
}
```

Seems like an explicit choice, but I don't think it's working as intended 🤔
