### ISSUE TITLE
lhci 0.9.0 autorun Unable to connect to Chrome

### ISSUE THREAD

**Issue by IanMoroney** [GoogleChrome/lighthouse-ci#799]
**Describe the bug**
Similar to #761, when I use 0.9.0, I get `unable to connect to Chrome`

**Expected behavior**
`0.9.0` should have ran the LHCI test.
Rolled back to `0.8.0` and it worked just fine.

**Logs/Screenshots**
```
+ export LHCI_BUILD_CONTEXT__COMMIT_TIME=2022-05-31T16:05:18+00:00
+ LHCI_BUILD_CONTEXT__COMMIT_TIME=2022-05-31T16:05:18+00:00
+ which lhci
/usr/local/bin/lhci
+ lhci healthcheck
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
Healthcheck passed!
+ lhci autorun --upload.serverBaseUrl=https://baseurl.com --upload.token=token --collect.url=https://www.collecturl --upload.basicAuth.username=username --upload.basicAuth.password=password
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
Healthcheck passed!

Running Lighthouse 3 time(s) on https://www.baseurl
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Tue, 31 May 2022 16:05:20 GMT ChromeLauncher Waiting for browser.
Tue, 31 May 2022 16:05:20 GMT ChromeLauncher Waiting for browser...
Tue, 31 May 2022 16:05:21 GMT ChromeLauncher Waiting for browser.....
Tue, 31 May 2022 16:05:21 GMT ChromeLauncher Waiting for browser.......
Tue, 31 May 2022 16:05:22 GMT ChromeLauncher Waiting for browser.........
Tue, 31 May 2022 16:05:22 GMT ChromeLauncher Waiting for browser...........
Tue, 31 May 2022 16:05:23 GMT ChromeLauncher Waiting for browser.............
Tue, 31 May 2022 16:05:23 GMT ChromeLauncher Waiting for browser...............
Tue, 31 May 2022 16:05:24 GMT ChromeLauncher Waiting for browser.................
Tue, 31 May 2022 16:05:24 GMT ChromeLauncher Waiting for browser...................
Tue, 31 May 2022 16:05:25 GMT ChromeLauncher Waiting for browser.....................
Tue, 31 May 2022 16:05:25 GMT ChromeLauncher Waiting for browser.......................
Tue, 31 May 2022 16:05:26 GMT ChromeLauncher Waiting for browser.........................
Tue, 31 May 2022 16:05:26 GMT ChromeLauncher Waiting for browser...........................
Tue, 31 May 2022 16:05:27 GMT ChromeLauncher Waiting for browser.............................
Tue, 31 May 2022 16:05:27 GMT ChromeLauncher Waiting for browser...............................
Tue, 31 May 2022 16:05:28 GMT ChromeLauncher Waiting for browser.................................
Tue, 31 May 2022 16:05:28 GMT ChromeLauncher Waiting for browser...................................
Tue, 31 May 2022 16:05:29 GMT ChromeLauncher Waiting for browser.....................................
Tue, 31 May 2022 16:05:29 GMT ChromeLauncher Waiting for browser.......................................
Tue, 31 May 2022 16:05:30 GMT ChromeLauncher Waiting for browser.........................................
Tue, 31 May 2022 16:05:30 GMT ChromeLauncher Waiting for browser...........................................
Tue, 31 May 2022 16:05:31 GMT ChromeLauncher Waiting for browser.............................................
Tue, 31 May 2022 16:05:31 GMT ChromeLauncher Waiting for browser...............................................
Tue, 31 May 2022 16:05:32 GMT ChromeLauncher Waiting for browser.................................................
Tue, 31 May 2022 16:05:32 GMT ChromeLauncher Waiting for browser...................................................
Tue, 31 May 2022 16:05:33 GMT ChromeLauncher Waiting for browser.....................................................
Tue, 31 May 2022 16:05:33 GMT ChromeLauncher Waiting for browser.......................................................
Tue, 31 May 2022 16:05:34 GMT ChromeLauncher Waiting for browser.........................................................
Tue, 31 May 2022 16:05:34 GMT ChromeLauncher Waiting for browser...........................................................
Tue, 31 May 2022 16:05:35 GMT ChromeLauncher Waiting for browser.............................................................
Tue, 31 May 2022 16:05:35 GMT ChromeLauncher Waiting for browser...............................................................
Tue, 31 May 2022 16:05:36 GMT ChromeLauncher Waiting for browser.................................................................
Tue, 31 May 2022 16:05:36 GMT ChromeLauncher Waiting for browser...................................................................
Tue, 31 May 2022 16:05:37 GMT ChromeLauncher Waiting for browser.....................................................................
Tue, 31 May 2022 16:05:37 GMT ChromeLauncher Waiting for browser.......................................................................
Tue, 31 May 2022 16:05:38 GMT ChromeLauncher Waiting for browser.........................................................................
Tue, 31 May 2022 16:05:38 GMT ChromeLauncher Waiting for browser...........................................................................
Tue, 31 May 2022 16:05:39 GMT ChromeLauncher Waiting for browser.............................................................................
Tue, 31 May 2022 16:05:39 GMT ChromeLauncher Waiting for browser...............................................................................
Tue, 31 May 2022 16:05:40 GMT ChromeLauncher Waiting for browser.................................................................................
Tue, 31 May 2022 16:05:40 GMT ChromeLauncher Waiting for browser...................................................................................
Tue, 31 May 2022 16:05:41 GMT ChromeLauncher Waiting for browser.....................................................................................
Tue, 31 May 2022 16:05:41 GMT ChromeLauncher Waiting for browser.......................................................................................
Tue, 31 May 2022 16:05:42 GMT ChromeLauncher Waiting for browser.........................................................................................
Tue, 31 May 2022 16:05:42 GMT ChromeLauncher Waiting for browser...........................................................................................
Tue, 31 May 2022 16:05:43 GMT ChromeLauncher Waiting for browser.............................................................................................
Tue, 31 May 2022 16:05:43 GMT ChromeLauncher Waiting for browser...............................................................................................
Tue, 31 May 2022 16:05:44 GMT ChromeLauncher Waiting for browser.................................................................................................
Tue, 31 May 2022 16:05:44 GMT ChromeLauncher Waiting for browser...................................................................................................
Tue, 31 May 2022 16:05:45 GMT ChromeLauncher Waiting for browser.....................................................................................................
Tue, 31 May 2022 16:05:45 GMT ChromeLauncher Waiting for browser.......................................................................................................
Tue, 31 May 2022 16:05:45 GMT ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:45657
Tue, 31 May 2022 16:05:45 GMT ChromeLauncher:error Logging contents of /tmp/lighthouse.15FZQvO/chrome-err.log
Tue, 31 May 2022 16:05:45 GMT ChromeLauncher:error [0531/160520.794928:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Failed to generate minidump.
Unable to connect to Chrome

```

**Environment:**
working:
 - OS: node:12-buster-slim
 - Browser chrome-stable
 - LHCI Version: 0.8.0

not working:
 - OS: 14-bullseye-slim, 14-buster-slim, 14-buster, 14-bullseye
 - Browser chrome-stable
 - LHCI Version 0.9.0

**Comment by PawFV** [comment]
Similar error, slightly different message, perhaps better to place it here.

![image](https://user-images.githubusercontent.com/44122984/172511316-68ec46b4-593c-4a53-98bf-41b1b9d4edab.png)

![image](https://user-images.githubusercontent.com/44122984/172511352-7fde5f0c-96c2-4c0a-875f-e5cf4f08cf0c.png)

**Comment by paulirish** [comment]
in configuration, you want to do ci.collect.settings.hostname of `127.0.0.1`

<img width="331" alt="image" src="https://user-images.githubusercontent.com/39191/187770262-c9ec5971-7c5d-419d-9409-fd91fe354e18.png">


Pretty sure that should sort it.  Apologies for this.
