### ISSUE TITLE
Suddenly uploading to Heroku stopped working with 500 error code

### ISSUE THREAD

**Issue by tniezurawski** [GoogleChrome/lighthouse-ci#804]
I'm not sure if that's a bug on lhci side or not so not raising it as a bug but looking for help.

Updating to my Heroku server worked perfectly for some time but I noticed an issue today. Uploading throws an error with `500` error code. I didn't change anything in the system. I can still access my LHCI server on Heroku and explore previous reports.

```
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
⚠️   Ancestor hash not determinable
✅  LHCI server reachable
✅  LHCI server API-compatible
✅  LHCI server token valid
✅  LHCI server can accept a build for this commit hash
Healthcheck passed!

Started a web server on port 43091...
Running Lighthouse 3 time(s) on http://localhost:43091/?perfMode#m=busy-salon
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!

Checking assertions against 1 URL(s), 3 total run(s)

All results processed!

Error: Unexpected status code 500
  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (/opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:79:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runLHCITarget (/opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/@lhci/cli/src/upload/upload.js:409:17)
    at async Object.runCommand (/opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/@lhci/cli/src/upload/upload.js:589:16)
Done running autorun.
    at async run (/opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/@lhci/cli/src/cli.js:109:7)WARNING: upload command failed.
```

**Does anyone know when this happens?**
Is there a way for me to recreate a request `lhci` does to my server and start debugging from there? (like knowing [the internal state of this function](https://github.com/GoogleChrome/lighthouse-ci/blob/main/packages/utils/src/api-client.js#L95-L100)).

----

EDIT: Here are the logs from the server. I removed timestamps and sensitive information:

```
---USER-REDACTED--- POST /v1/projects/---ID-REDACTED---/builds HTTP/1.1 500 148 - 15.471 ms
app[web.1]: SequelizeDatabaseError: permission denied for table builds
app[web.1]: at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
app[web.1]: at /app/node_modules/sequelize/lib/dialects/postgres/query.js:86:18
app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
app[web.1]: at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
app[web.1]: at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
app[web.1]: at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
app[web.1]: at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
app[web.1]: at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
app[web.1]: at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
app[web.1]: at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
app[web.1]: at processImmediate (node:internal/timers:466:21)
```

As far as I understand no permission to `builds` table 🤔

**Comment by tniezurawski** [comment]
**Solution.** Actually, not a _solution_ but a reason and a hint for people that arrived here.

My hobby project used the limit of the Postgres database:

![image](https://user-images.githubusercontent.com/4335166/173589122-f01a5291-2c96-4d34-913a-3455c6018c96.png)

Clearing data and setting up the project or upgrading the DB fixes the issue.
