### ISSUE TITLE
Setting basic auth for lhci server throws Error: listen EADDRINUSE: address already in use :::9001

### ISSUE THREAD

**Issue by KevBat** [GoogleChrome/lighthouse-ci#833]
**Describe the bug**
After running through the lhci wizard, adding a new project and uploading lighthouse results to the server, I went back to the container to add basic auth. 

Running the command 

```
lhci server --basicAuth.username=xxxxxxx --basicAuth.password=xxxxxxx 
```
Resulted in the following exception 

```
Error: listen EADDRINUSE: address already in use :::9001
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at /usr/src/lhci/node_modules/@lhci/server/src/server.js:102:12
    at new Promise (<anonymous>)
    at createServer (/usr/src/lhci/node_modules/@lhci/server/src/server.js:78:10)
    at async run (/usr/src/lhci/node_modules/@lhci/cli/src/cli.js:118:22)
```

**To Reproduce**
1. Run lhci server docker container in Azure container instance
2. Run lhci wizard in container and setup a new project
3. Upload report to the server
4. In container shell, run lhci server --basicAuth.username=x --basicAuth.password=y

**Expected behavior**
Basic auth successfully created with supplied credentials

**Logs/Screenshots**
If applicable, add LHCI logs or screenshots to help explain your problem.

**Environment (please complete the following information):**

**Additional context**

**Comment by KevBat** [comment]
**workaround**

After digging a bit I believe this is because the application is already running in the container. Because killing the node pid in the container will kill the shell, the workaround I figured out was to pass the creds as extra vars to the docker run command. In my particular case I'm using Terraform to deploy the docker image to azure container instances. 

Sample terraform code below (recommend to have password added as part of your ci/cd process so it's not in plain text)

```
resource "azurerm_container_group" "main" {
...
  container {
    name   = "lighthouse"
    image  = "patrickhulce/lhci-server:latest"
    cpu    = "0.5"
    memory = "1.5"
...
    secure_environment_variables = {
      "LHCI_BASIC_AUTH__USERNAME" = "example"
      "LHCI_BASIC_AUTH__PASSWORD" = "<password inserted by ci/cd>"
    }
...
}
```
