### ISSUE TITLE
Local autorun for a Vue applicatoin fails to upload report data to lhci server

### ISSUE THREAD

**Issue by knoxilla** [GoogleChrome/lighthouse-ci#847]
**Describe the bug**
When using lhci/cli version 0.10 (for both server and client) I cannot upload report data to an LHCI server running in the cloud.  The first run of `lhci autorun` yields a clean healthcheck but gets a 403 error on upload.  Subsequent attempts say that the server already had data for the current git commit hash.  But it failed, so how can it have it?

**To Reproduce**
1. Install and configure lhci/cli in your project
2. Use lighthouserc.json to configure the target LHCI custom server
3. Invoke `lhci autorun` and

**Expected behavior**
The report should have been uploaded!  This used to work under version 0.9

**Logs/Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: N/A
 - Version of lhci/cli 0.10

**Additional context**

Here is the result of the first run:

```bash
$ lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
⚠️   GitHub token not set
✅  Ancestor hash determinable
✅  LHCI server reachable
✅  LHCI server API-compatible
✅  LHCI server token valid
✅  LHCI server can accept a build for this commit hash
Healthcheck passed!

Started a web server with "npm run dev"...
Running Lighthouse 1 time(s) on http://127.0.0.1:5173
Run #1...done.
Done running Lighthouse!

Checking assertions against 1 URL(s), 1 total run(s)

All results processed!

Saving CI project rad-vue-project (726a623f-4200-4d4a-a3a9-8dd1b2e4ef43)
Saving CI build (87096dd3-3103-454d-9ce6-88335bf3e3e2)
Error: Unexpected status code 403
  <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (/usr/local/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:79:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runLHCITarget (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:438:17)
    at async Object.runCommand (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:590:16)
    at async run (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:106:7)
WARNING: upload command failed.
Done running autorun.
```

A second run gets this result in the healthcheck phase:

```
⚠️   LHCI server already has a build for this commit hash
```

Version info

```
$ lhci --version
0.10.0
$ curl https://lhci.customhost.dev/version
0.10.0
```

lighthouserc.json
```js
module.exports = {
  ci: {
    collect: {
      startServerCommand: 'npm run dev',
      url: ['http://127.0.0.1:5173'],
      numberOfRuns: 3,
    },
     assert: {
      assertions: {
        'categories:performance': ['warn', {minScore: 1}],
        'categories:accessibility': ['warn', {minScore: 1}],
        'categories:seo': ['warn', {minScore: .92}]
      }
    },
    upload: {
      "target": "lhci",
      "token": "xxx-xxx-xxx-xxx",
      "serverBaseUrl": "https://lhci.customhost.dev/",
    },
  },
```

**Comment by codeflorist** [comment]
Regarding first error `403 Forbidden`:

Is your lighthouse server protected by basic auth? if yes, you need to provide it's credentials:
`lhci autorun --upload.basicAuth.username="###" --upload.basicAuth.password="###"`
(i suppose you could also put that inside `lighthouserc.json`, although i would not put the password inside a version-controlled file.)

Regarding second error `LHCI server already has a build for this commit hash`:

the upload-flag `ignoreDuplicateBuildFailure` should get rid of this error, e.g. via command line parameter:
`lhci autorun --upload.ignoreDuplicateBuildFailure`
or in your `lighthouserc.json`:
```js
    upload: {
      ....
      ignoreDuplicateBuildFailure: true
    },
```
