### ISSUE TITLE
Unable to upload run results to local LHCI server

### ISSUE THREAD

**Issue by wole-ada** [GoogleChrome/lighthouse-ci#850]
**Describe the bug**
Running into Sequelize readonly errors when attempting to upload test results to a local LHCI server (exposed using ngrok) using a GH action

**To Reproduce**
1. Set up a LHCI server using the instructions [here](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/server.md#general)
2. Create a GH action job for running the Lighthouse tests using the instructions [here](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#configure-your-ci-provider)
3. Ensure the lighthouserc.js file is configured to upload results to the LCHI server created previously
4. Trigger the job in CI
5. See the following error after the test runs, when trying to upload the results: `SequelizeDatabaseError: SQLITE_READONLY: attempt to write a readonly database`

**Expected behavior**
The results should be uploaded to the server successfully

**Logs/Screenshots**
```
Error: Unexpected status code 500
  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SequelizeDatabaseError: SQLITE_READONLY: attempt to write a readonly database<br> &nbsp; &nbsp;at Query.formatError (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)<br> &nbsp; &nbsp;at Statement.afterExecute (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)<br> &nbsp; &nbsp;at Statement.wrappedAfterExecute (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)<br> &nbsp; &nbsp;at Statement.replacement (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sqlite3/lib/trace.js:25:27)<br>From previous event:<br> &nbsp; &nbsp;at executeSql (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:107:21)<br> &nbsp; &nbsp;at Database.&lt;anonymous&gt; (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:305:18)<br> &nbsp; &nbsp;at /Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:102:21<br>From previous event:<br> &nbsp; &nbsp;at Query.run (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/dialects/sqlite/query.js:100:12)<br> &nbsp; &nbsp;at /Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/sequelize.js:561:20<br>From previous event:<br> &nbsp; &nbsp;at /Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/sequelize.js:558:8<br> &nbsp; &nbsp;at /Users/oluwoleobayomi/AdaSupport/chat/node_modules/retry-as-promised/index.js:39:21<br> &nbsp; &nbsp;at retryAsPromised (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/retry-as-promised/index.js:29:10)<br> &nbsp; &nbsp;at Sequelize.query (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/sequelize.js:457:28)<br> &nbsp; &nbsp;at QueryInterface.insert (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/query-interface.js:901:27)<br> &nbsp; &nbsp;at /Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/model.js:3685:53<br> &nbsp; &nbsp;at processImmediate (node:internal/timers:466:21)<br>From previous event:<br> &nbsp; &nbsp;at model.save (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/model.js:3661:8)<br> &nbsp; &nbsp;at Function.create (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/sequelize/lib/model.js:2023:8)<br> &nbsp; &nbsp;at SqlStorageMethod.createBuild (/Users/oluwoleobayomi/AdaSupport/chat/node_modules/@lhci/server/src/api/storage/sql/sql.js:[42](https://github.com/AdaSupport/chat/actions/runs/3677248629/jobs/6219001513#step:4:43)9:36)<br> &nbsp; &nbsp;at async /Users/oluwoleobayomi/AdaSupport/chat/node_modules/@lhci/server/src/api/routes/projects.js:132:21</pre>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (/opt/hostedtoolcache/node/16.18.1/x64/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:79:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runLHCITarget (/opt/hostedtoolcache/node/16.18.1/x64/lib/node_modules/@lhci/cli/src/upload/upload.js:409:17)
    at async Object.runCommand (/opt/hostedtoolcache/node/16.18.1/x64/lib/node_modules/@lhci/cli/src/upload/upload.js:592:16)
```

**Environment (please complete the following information):**
 - OS: ubuntu-latest runner (GH action)
 - @lhci/server: 0.10.0
 - @lhci/cli: 0.8.x

**Additional context**
This behavior is not exhibited locally. Tests run and the result are uploaded to the local LHCI server with no issue.
In GH CI, the tests run successfully but fail with the error shown above (attempt to write a readonly database)

Looking for assistance in resolving this issue in Github CI

### lighthouserc.js
```
module.exports = {
  ci: {
    collect: {
      url: ["https://some-remote-endpoint.com"],
    },
    upload: {
      target: 'lhci',
      serverBaseUrl: 'https://xxxxxx.ngrok.io',
      token: process.env.LHCI_TOKEN
    },
  },
};
```

**Comment by wole-ada** [comment]
It seems this happens if the `db.sql` file being written to by the server, was created by the client.
I had a `db.sql` file that was created when I ran `lhci autorun` locally. After deleting that, creating a new project and running the test in CI, the results were successfully uploaded to the local LHCI server
