### ISSUE TITLE
unable to rotate the build token through lhci wizard

### ISSUE THREAD

**Issue by AditiGupta-ag** [GoogleChrome/lighthouse-ci#864]
I am trying to rotate build token for my app (hosted in heroku) , after trying multiple things still local is not able to connect with database, and giving error like:

after doing lhci wizard
(error 👇)

Error: Storage method "undefined" not yet supported
at StorageMethod.from (/Users/aditigupta/node_modules/@lhci/server/src/api/storage/storage-method.js:427:15)
at runResetTokenWizard (/Users/aditigupta/.volta/tools/image/packages/@lhci/cli/lib/node_modules/@lhci/cli/src/wizard/wizard.js:104:39)
at Object.runCommand (/Users/aditigupta/.volta/tools/image/packages/@lhci/cli/lib/node_modules/@lhci/cli/src/wizard/wizard.js:167:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async run (/Users/aditigupta/.volta/tools/image/packages/@lhci/cli/lib/node_modules/@lhci/cli/src/cli.js:125:7)%

another command which I tried
lhci server --storage.sqlDialect=postgres --storage.sqlConnectionUrl="postgres://ub9*******:pb************@ec2-*****:543"
(error 👇)

SequelizeConnectionError: no pg_hba.conf entry for host "", user "", database "*******", SSL off
at Client._connectionCallback (/Users/aditigupta/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:154:24)
at Client._handleErrorWhileConnecting (/Users/aditigupta/node_modules/pg/lib/client.js:305:19)
at Client._handleErrorMessage (/Users/aditigupta/node_modules/pg/lib/client.js:325:19)
at Connection.emit (node:events:513:28)
at /Users/aditigupta/node_modules/pg/lib/connection.js:114:12
at Parser.parse (/Users/aditigupta/node_modules/pg-protocol/dist/parser.js:40:17)
at Socket. (/Users/aditigupta/node_modules/pg-protocol/dist/index.js:11:42)
at Socket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)%

even after doing
lhci server --basicAuth.username=ub90******** --basicAuth.password=pb*********
(error is like 👇)

SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
at Client._connectionCallback (/Users/aditigupta/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:142:24)
at Client._handleErrorWhileConnecting (/Users/aditigupta/node_modules/pg/lib/client.js:305:19)
at Client._handleErrorEvent (/Users/aditigupta/node_modules/pg/lib/client.js:315:19)
at Connection.emit (node:events:513:28)
at Socket.reportStreamError (/Users/aditigupta/node_modules/pg/lib/connection.js:52:12)
at Socket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)%

**Comment by duffn** [comment]
Resetting the token works for me if I just pass the `sql` storage method. 

```
./node_modules/.bin/lhci --storage.storageMethod=sql wizard
```
